import { Lobster } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

const lobster = Lobster({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lobster',
});

export const metadata = {
  title: "El Zarape",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${lobster.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <Navbar/>

          {children}
          
          <Footer/>
      </body>
    </html>
  );
}
